theme: jekyll-theme-cayman

title: [SmartDogHouse]
description: [The best dog house!]
show_downloads: true
github:
  zip_url: https://github.com/scalaquest/PPS-19-ScalaQuest/releases/latest
  tar_url: https://github.com/scalaquest/PPS-19-ScalaQuest/releases/latest
