theme: jekyll-theme-cayman

title: [SmartDogHouse]
description: [The best dog house!]
show_downloads: true
github:
  zip_url: https://github.com/camillo2008/pps1920-motoScala-report/releases/latest
  tar_url: https://github.com/camillo2008/pps1920-motoScala-report/releases/latest
