# This is a basic workflow to help you get started with Actions
name: Latek Build
on:
  push:
    branches: [ master ]
    tags:
      - '**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_latek:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Test
        shell: bash
        id: tes
        run: echo "::set-output name=RELESE_NAME::$(echo ${{github.event.head_commit.message}} | grep -o -P '(?<=-TAG{).*(?=})')"
      - name: Test1
        shell: bash
        run: echo ${{steps.tes.outputs.RELESE_NAME}}
      - name: Setup Git repo
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          #pre_compile: "tlmgr update --self --all"
          args: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode -logfilewarninglist -Werror"
          post_compile: "latexmk -c"
      
      - name: Split log
        if: failure()
        shell: bash
        run: cat main.log | grep -n -E 'LaTeX Error|LaTeX Warning|Undefined' > small.log
      
      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: Logs
          path: |
            main.log
            small.log
            
      - name: Print small log
        if: failure()
        shell: bash
        run: cat small.log >&2
        
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: main.pdf
          
      - name: Check if Git tag exists
        id: check_tag
        run: echo "::set-output name=HEAD_TAG::$(git describe --tags --exact-match HEAD)"
        #echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//} alternativa da testare?
      - name: Create relese if tag commit contain a tag message
        if: ${{ steps.tes.outputs.RELESE_NAME != '' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ steps.tes.outputs.RELESE_NAME }}
          release_name: Release ${{ steps.tes.outputs.RELESE_NAME }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Deploy only if tag is present
        shell: bash
        if: ${{steps.check_tag.outputs.HEAD_TAG != '' && success() && failure() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --tags -f
          TAG=$(git describe --tags --exact-match HEAD)
          hub release create -m "$(git tag -l --format='%(contents)' "$TAG")" "$TAG" || true   
          for pdfs in *.pdf; do 
            echo "\n\nDelivering file $pdfs \n\n"
            hub release edit -m '' -a "$pdfs" "$TAG"
          done
